name: Build & Deploy Jays Spring App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring Boot App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Unit Tests
      run: mvn -B test --file pom.xml

# the pipe | is for when you want to write multiple commands in one run step. Like clean and package.
    - name: Build the application
      run: |
        mvn clean
        mvn -B package --file pom.xml
